# Generated by github.com/davyxu/gosproto/pb2sproto
# Source: pb.proto



.MyCar {
		
	Monkey 0
		
	Monk 1
		
	Pig 2
	
}



# This is phone number
.PhoneNumber {
		
	Number 1 : string # mobile phone number
		
	Type 2 : int32 # phone type
	
}

# Person
.Person {
		
	Name 1 : string 
		
	Id 2 : int32 
		
	Email 3 : string 
		
	phone 4 : *PhoneNumber 
		
	Staff 5 : boolean 
	
}

# All person list
.AddressBook {
		
	person 1 : *Person 
	
}

