// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: behavior.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.BehaviorDefine", (*BehaviorDefine)(nil), 791402043)
	cellnet.RegisterMessageMeta("gamedef.BehaviorFile", (*BehaviorFile)(nil), 2539894295)
}
