// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: channel.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.ChannelDefine", (*ChannelDefine)(nil))
	cellnet.RegisterMessageMeta("gamedef.ChannelFile", (*ChannelFile)(nil))
}
