// This code is generated by github.com/davyxu/cellnet/protoc-gen-msg, DO NOT EDIT
// Generated from: channel.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessage("gamedef.ChannelDefine", (*ChannelDefine)(nil))
	cellnet.RegisterMessage("gamedef.ChannelFile", (*ChannelFile)(nil))
}
