// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: game.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.EnterGameREQ", (*EnterGameREQ)(nil), 1204407910)
	cellnet.RegisterMessageMeta("gamedef.EnterGameACK", (*EnterGameACK)(nil), 747844100)
}
