// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: game.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.EnterGameREQ", (*EnterGameREQ)(nil))
	cellnet.RegisterMessageMeta("gamedef.EnterGameACK", (*EnterGameACK)(nil))
}
