// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: login.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.LoginREQ", (*LoginREQ)(nil))
	cellnet.RegisterMessageMeta("gamedef.ServerInfo", (*ServerInfo)(nil))
	cellnet.RegisterMessageMeta("gamedef.LoginACK", (*LoginACK)(nil))
}
