// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: login.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.LoginREQ", (*LoginREQ)(nil), 1948892914)
	cellnet.RegisterMessageMeta("gamedef.ServerInfo", (*ServerInfo)(nil), 3950476513)
	cellnet.RegisterMessageMeta("gamedef.LoginACK", (*LoginACK)(nil), 527647376)
}
