// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: login.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.LoginREQ", (*LoginREQ)(nil), 898551513)
	cellnet.RegisterMessageMeta("gamedef.ServerInfo", (*ServerInfo)(nil), 1107174966)
	cellnet.RegisterMessageMeta("gamedef.LoginACK", (*LoginACK)(nil), 1590964923)
}
