// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: model.proto
	// login.proto
	// game.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.LoginModel", (*LoginModel)(nil), 3486131741)
	cellnet.RegisterMessageMeta("gamedef.ModelACK", (*ModelACK)(nil), 1600596047)
}
