// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: model.proto
	// login.proto
	// game.proto
	// char.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.LoginModel", (*LoginModel)(nil), 3486131741)
	cellnet.RegisterMessageMeta("gamedef.ModelACK", (*ModelACK)(nil), 1600596047)
	cellnet.RegisterMessageMeta("gamedef.ModelValue", (*ModelValue)(nil), 2022143253)
	cellnet.RegisterMessageMeta("gamedef.ModelSyncACK", (*ModelSyncACK)(nil), 3598711227)
}
