// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: model.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.TestAccountData", (*TestAccountData)(nil), 3608077311)
	cellnet.RegisterMessageMeta("gamedef.TestEquipData", (*TestEquipData)(nil), 1792671458)
	cellnet.RegisterMessageMeta("gamedef.TestRoleData", (*TestRoleData)(nil), 270638963)
	cellnet.RegisterMessageMeta("gamedef.ModelACK", (*ModelACK)(nil), 515922020)
	cellnet.RegisterMessageMeta("gamedef.TestModelCommandACK", (*TestModelCommandACK)(nil), 581674490)
}
