// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: router.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.UpstreamACK", (*UpstreamACK)(nil), 3582740848)
	cellnet.RegisterMessageMeta("gamedef.CloseClientACK", (*CloseClientACK)(nil), 3483582153)
	cellnet.RegisterMessageMeta("gamedef.DownstreamACK", (*DownstreamACK)(nil), 487544680)
	cellnet.RegisterMessageMeta("gamedef.RegisterRouterBackendACK", (*RegisterRouterBackendACK)(nil), 3288936586)
}
