// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: router.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.UpstreamACK", (*UpstreamACK)(nil), 1704656533)
	cellnet.RegisterMessageMeta("gamedef.CloseClientACK", (*CloseClientACK)(nil), 2995936107)
	cellnet.RegisterMessageMeta("gamedef.DownstreamACK", (*DownstreamACK)(nil), 2028020128)
	cellnet.RegisterMessageMeta("gamedef.RegisterRouterBackendACK", (*RegisterRouterBackendACK)(nil), 2210534204)
}
