// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: service.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessage("gamedef.ServiceDefine", (*ServiceDefine)(nil))
	cellnet.RegisterMessage("gamedef.ServiceFile", (*ServiceFile)(nil))
	cellnet.RegisterMessage("gamedef.LocalConfig", (*LocalConfig)(nil))
}
