// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: service.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("gamedef.ServiceDefine", (*ServiceDefine)(nil), 419771465)
	cellnet.RegisterMessageMeta("gamedef.ServiceFile", (*ServiceFile)(nil), 2884989903)
	cellnet.RegisterMessageMeta("gamedef.LocalFile", (*LocalFile)(nil), 2730603477)
}
