// This code is generated by github.com/davyxu/cellnet/protoc-gen-msg, DO NOT EDIT
// Generated from: tool.proto
package gamedef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessage("gamedef.TableCodeOption", (*TableCodeOption)(nil))
}
