package main

const emmyluaCodeTemplate = `-- Generated by github.com/davyxu/gosproto/sprotogen
-- DO NOT EDIT!

{{range .Structs}}
---@class {{.Name}} {{range .StFields}}
---@field public {{.Name}} {{.CSTypeName}} {{end}}
local {{.Name}} = {}
{{end}}

`

func gen_emmylua(fm *fileModel, filename string) {

	addData(fm, "lua")

	generateCode("sp->emmylua", emmyluaCodeTemplate, filename, fm, nil)

}
