// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: addressbook.proto
namespace tutorial
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhoneNumber")]
	public partial class PhoneNumber : global::ProtoBuf.IExtensible
	{
		
		
		public PhoneNumber() {}
		
		string _number = "";
		bool _hasnumber = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string number
		{
			get { return _number; }
			set { _number = value; 
			      _hasnumber = true;
			}
		}
		
		public bool Hasnumber
		{
			get { return _hasnumber; }
			set { _hasnumber = value; }
		}
		
		tutorial.PhoneType _type = tutorial.PhoneType.MOBILE;
		bool _hastype = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(tutorial.PhoneType.MOBILE)]
		public tutorial.PhoneType type
		{
			get { return _type; }
			set { _type = value; 
			      _hastype = true;
			}
		}
		
		public bool Hastype
		{
			get { return _hastype; }
			set { _hastype = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Person")]
	public partial class Person : global::ProtoBuf.IExtensible
	{
		
		
		public Person() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		int _id = default(int);
		bool _hasid = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int id
		{
			get { return _id; }
			set { _id = value; 
			      _hasid = true;
			}
		}
		
		public bool Hasid
		{
			get { return _hasid; }
			set { _hasid = value; }
		}
		
		string _email = "";
		bool _hasemail = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string email
		{
			get { return _email; }
			set { _email = value; 
			      _hasemail = true;
			}
		}
		
		public bool Hasemail
		{
			get { return _hasemail; }
			set { _hasemail = value; }
		}
		
		readonly global::System.Collections.Generic.List<tutorial.PhoneNumber> _phone = new global::System.Collections.Generic.List<tutorial.PhoneNumber>();
		[global::ProtoBuf.ProtoMember(4, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<tutorial.PhoneNumber> phone
		{
			get { return _phone; }
		}
		
		
		readonly global::System.Collections.Generic.List<int> _test = new global::System.Collections.Generic.List<int>();
		[global::ProtoBuf.ProtoMember(5, Name=@"test", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public global::System.Collections.Generic.List<int> test
		{
			get { return _test; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddressBook")]
	public partial class AddressBook : global::ProtoBuf.IExtensible
	{
		
		
		public AddressBook() {}
		
		readonly global::System.Collections.Generic.List<tutorial.Person> _person = new global::System.Collections.Generic.List<tutorial.Person>();
		[global::ProtoBuf.ProtoMember(1, Name=@"person", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<tutorial.Person> person
		{
			get { return _person; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
	[global::ProtoBuf.ProtoContract(Name=@"PhoneType")]
	public enum PhoneType
	{
		[global::ProtoBuf.ProtoEnum(Name=@"MOBILE", Value=0)]
		MOBILE = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"HOME", Value=1)]
		HOME = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"WORK", Value=2)]
		WORK = 2
		
	}
}
