// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: client.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginSetting")]
	public partial class LoginSetting : global::ProtoBuf.IExtensible
	{
		public LoginSetting() {}
		
		private string _Account = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Account
		{
			get { return _Account; }
			set { _Account = value; }
		}
		
		private string _Address = "";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Address
		{
			get { return _Address; }
			set { _Address = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
