// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: descriptor.proto
namespace google.protobuf
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileDescriptorSet")]
	public partial class FileDescriptorSet : global::ProtoBuf.IExtensible
	{
		
		
		public FileDescriptorSet() {}
		
		readonly global::System.Collections.Generic.List<google.protobuf.FileDescriptorProto> _file = new global::System.Collections.Generic.List<google.protobuf.FileDescriptorProto>();
		[global::ProtoBuf.ProtoMember(1, Name=@"file", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.FileDescriptorProto> file
		{
			get { return _file; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileDescriptorProto")]
	public partial class FileDescriptorProto : global::ProtoBuf.IExtensible
	{
		
		
		public FileDescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		string _package = "";
		bool _haspackage = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string package
		{
			get { return _package; }
			set { _package = value; 
			      _haspackage = true;
			}
		}
		
		public bool Haspackage
		{
			get { return _haspackage; }
			set { _haspackage = value; }
		}
		
		readonly global::System.Collections.Generic.List<string> _dependency = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(3, Name=@"dependency", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> dependency
		{
			get { return _dependency; }
		}
		
		
		readonly global::System.Collections.Generic.List<int> _public_dependency = new global::System.Collections.Generic.List<int>();
		[global::ProtoBuf.ProtoMember(10, Name=@"public_dependency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public global::System.Collections.Generic.List<int> public_dependency
		{
			get { return _public_dependency; }
		}
		
		
		readonly global::System.Collections.Generic.List<int> _weak_dependency = new global::System.Collections.Generic.List<int>();
		[global::ProtoBuf.ProtoMember(11, Name=@"weak_dependency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public global::System.Collections.Generic.List<int> weak_dependency
		{
			get { return _weak_dependency; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.DescriptorProto> _message_type = new global::System.Collections.Generic.List<google.protobuf.DescriptorProto>();
		[global::ProtoBuf.ProtoMember(4, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.DescriptorProto> message_type
		{
			get { return _message_type; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> _enum_type = new global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto>();
		[global::ProtoBuf.ProtoMember(5, Name=@"enum_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> enum_type
		{
			get { return _enum_type; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.ServiceDescriptorProto> _service = new global::System.Collections.Generic.List<google.protobuf.ServiceDescriptorProto>();
		[global::ProtoBuf.ProtoMember(6, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.ServiceDescriptorProto> service
		{
			get { return _service; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> _extension = new global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto>();
		[global::ProtoBuf.ProtoMember(7, Name=@"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> extension
		{
			get { return _extension; }
		}
		
		
		google.protobuf.FileOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.FileOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		google.protobuf.SourceCodeInfo _source_code_info = null;
		bool _hassource_code_info = false;
		[global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"source_code_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.SourceCodeInfo source_code_info
		{
			get { return _source_code_info; }
			set { _source_code_info = value; 
			      _hassource_code_info = true;
			}
		}
		
		public bool Hassource_code_info
		{
			get { return _hassource_code_info; }
			set { _hassource_code_info = value; }
		}
		
		string _syntax = "";
		bool _hassyntax = false;
		[global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"syntax", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string syntax
		{
			get { return _syntax; }
			set { _syntax = value; 
			      _hassyntax = true;
			}
		}
		
		public bool Hassyntax
		{
			get { return _hassyntax; }
			set { _hassyntax = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DescriptorProto")]
	public partial class DescriptorProto : global::ProtoBuf.IExtensible
	{
		
		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExtensionRange")]
		public partial class ExtensionRange : global::ProtoBuf.IExtensible
		{
			
			
			public ExtensionRange() {}
			
			int _start = default(int);
			bool _hasstart = false;
			[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int start
			{
				get { return _start; }
				set { _start = value; 
				      _hasstart = true;
				}
			}
			
			public bool Hasstart
			{
				get { return _hasstart; }
				set { _hasstart = value; }
			}
			
			int _end = default(int);
			bool _hasend = false;
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int end
			{
				get { return _end; }
				set { _end = value; 
				      _hasend = true;
				}
			}
			
			public bool Hasend
			{
				get { return _hasend; }
				set { _hasend = value; }
			}
			
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}
		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReservedRange")]
		public partial class ReservedRange : global::ProtoBuf.IExtensible
		{
			
			
			public ReservedRange() {}
			
			int _start = default(int);
			bool _hasstart = false;
			[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int start
			{
				get { return _start; }
				set { _start = value; 
				      _hasstart = true;
				}
			}
			
			public bool Hasstart
			{
				get { return _hasstart; }
				set { _hasstart = value; }
			}
			
			int _end = default(int);
			bool _hasend = false;
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int end
			{
				get { return _end; }
				set { _end = value; 
				      _hasend = true;
				}
			}
			
			public bool Hasend
			{
				get { return _hasend; }
				set { _hasend = value; }
			}
			
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}
		
		public DescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> _field = new global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto>();
		[global::ProtoBuf.ProtoMember(2, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> field
		{
			get { return _field; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> _extension = new global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto>();
		[global::ProtoBuf.ProtoMember(6, Name=@"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> extension
		{
			get { return _extension; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.DescriptorProto> _nested_type = new global::System.Collections.Generic.List<google.protobuf.DescriptorProto>();
		[global::ProtoBuf.ProtoMember(3, Name=@"nested_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.DescriptorProto> nested_type
		{
			get { return _nested_type; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> _enum_type = new global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto>();
		[global::ProtoBuf.ProtoMember(4, Name=@"enum_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> enum_type
		{
			get { return _enum_type; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ExtensionRange> _extension_range = new global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ExtensionRange>();
		[global::ProtoBuf.ProtoMember(5, Name=@"extension_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ExtensionRange> extension_range
		{
			get { return _extension_range; }
		}
		
		
		readonly global::System.Collections.Generic.List<google.protobuf.OneofDescriptorProto> _oneof_decl = new global::System.Collections.Generic.List<google.protobuf.OneofDescriptorProto>();
		[global::ProtoBuf.ProtoMember(8, Name=@"oneof_decl", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.OneofDescriptorProto> oneof_decl
		{
			get { return _oneof_decl; }
		}
		
		
		google.protobuf.MessageOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.MessageOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ReservedRange> _reserved_range = new global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ReservedRange>();
		[global::ProtoBuf.ProtoMember(9, Name=@"reserved_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ReservedRange> reserved_range
		{
			get { return _reserved_range; }
		}
		
		
		readonly global::System.Collections.Generic.List<string> _reserved_name = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(10, Name=@"reserved_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> reserved_name
		{
			get { return _reserved_name; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FieldDescriptorProto")]
	public partial class FieldDescriptorProto : global::ProtoBuf.IExtensible
	{
		
		
		public FieldDescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		int _number = default(int);
		bool _hasnumber = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int number
		{
			get { return _number; }
			set { _number = value; 
			      _hasnumber = true;
			}
		}
		
		public bool Hasnumber
		{
			get { return _hasnumber; }
			set { _hasnumber = value; }
		}
		
		google.protobuf.FieldDescriptorProto.Label _label = google.protobuf.FieldDescriptorProto.Label.LABEL_OPTIONAL;
		bool _haslabel = false;
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(google.protobuf.FieldDescriptorProto.Label.LABEL_OPTIONAL)]
		public google.protobuf.FieldDescriptorProto.Label label
		{
			get { return _label; }
			set { _label = value; 
			      _haslabel = true;
			}
		}
		
		public bool Haslabel
		{
			get { return _haslabel; }
			set { _haslabel = value; }
		}
		
		google.protobuf.FieldDescriptorProto.Type _type = google.protobuf.FieldDescriptorProto.Type.TYPE_DOUBLE;
		bool _hastype = false;
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(google.protobuf.FieldDescriptorProto.Type.TYPE_DOUBLE)]
		public google.protobuf.FieldDescriptorProto.Type type
		{
			get { return _type; }
			set { _type = value; 
			      _hastype = true;
			}
		}
		
		public bool Hastype
		{
			get { return _hastype; }
			set { _hastype = value; }
		}
		
		string _type_name = "";
		bool _hastype_name = false;
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string type_name
		{
			get { return _type_name; }
			set { _type_name = value; 
			      _hastype_name = true;
			}
		}
		
		public bool Hastype_name
		{
			get { return _hastype_name; }
			set { _hastype_name = value; }
		}
		
		string _extendee = "";
		bool _hasextendee = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"extendee", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string extendee
		{
			get { return _extendee; }
			set { _extendee = value; 
			      _hasextendee = true;
			}
		}
		
		public bool Hasextendee
		{
			get { return _hasextendee; }
			set { _hasextendee = value; }
		}
		
		string _default_value = "";
		bool _hasdefault_value = false;
		[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"default_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string default_value
		{
			get { return _default_value; }
			set { _default_value = value; 
			      _hasdefault_value = true;
			}
		}
		
		public bool Hasdefault_value
		{
			get { return _hasdefault_value; }
			set { _hasdefault_value = value; }
		}
		
		int _oneof_index = default(int);
		bool _hasoneof_index = false;
		[global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"oneof_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int oneof_index
		{
			get { return _oneof_index; }
			set { _oneof_index = value; 
			      _hasoneof_index = true;
			}
		}
		
		public bool Hasoneof_index
		{
			get { return _hasoneof_index; }
			set { _hasoneof_index = value; }
		}
		
		string _json_name = "";
		bool _hasjson_name = false;
		[global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"json_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string json_name
		{
			get { return _json_name; }
			set { _json_name = value; 
			      _hasjson_name = true;
			}
		}
		
		public bool Hasjson_name
		{
			get { return _hasjson_name; }
			set { _hasjson_name = value; }
		}
		
		google.protobuf.FieldOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.FieldOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		[global::ProtoBuf.ProtoContract(Name=@"Type")]
		public enum Type
		{
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_DOUBLE", Value=1)]
			TYPE_DOUBLE = 1,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_FLOAT", Value=2)]
			TYPE_FLOAT = 2,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_INT64", Value=3)]
			TYPE_INT64 = 3,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_UINT64", Value=4)]
			TYPE_UINT64 = 4,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_INT32", Value=5)]
			TYPE_INT32 = 5,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_FIXED64", Value=6)]
			TYPE_FIXED64 = 6,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_FIXED32", Value=7)]
			TYPE_FIXED32 = 7,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_BOOL", Value=8)]
			TYPE_BOOL = 8,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_STRING", Value=9)]
			TYPE_STRING = 9,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_GROUP", Value=10)]
			TYPE_GROUP = 10,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_MESSAGE", Value=11)]
			TYPE_MESSAGE = 11,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_BYTES", Value=12)]
			TYPE_BYTES = 12,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_UINT32", Value=13)]
			TYPE_UINT32 = 13,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_ENUM", Value=14)]
			TYPE_ENUM = 14,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_SFIXED32", Value=15)]
			TYPE_SFIXED32 = 15,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_SFIXED64", Value=16)]
			TYPE_SFIXED64 = 16,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_SINT32", Value=17)]
			TYPE_SINT32 = 17,
			
			[global::ProtoBuf.ProtoEnum(Name=@"TYPE_SINT64", Value=18)]
			TYPE_SINT64 = 18
			
		}
		[global::ProtoBuf.ProtoContract(Name=@"Label")]
		public enum Label
		{
			[global::ProtoBuf.ProtoEnum(Name=@"LABEL_OPTIONAL", Value=1)]
			LABEL_OPTIONAL = 1,
			
			[global::ProtoBuf.ProtoEnum(Name=@"LABEL_REQUIRED", Value=2)]
			LABEL_REQUIRED = 2,
			
			[global::ProtoBuf.ProtoEnum(Name=@"LABEL_REPEATED", Value=3)]
			LABEL_REPEATED = 3
			
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneofDescriptorProto")]
	public partial class OneofDescriptorProto : global::ProtoBuf.IExtensible
	{
		
		
		public OneofDescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		google.protobuf.OneofOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.OneofOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumDescriptorProto")]
	public partial class EnumDescriptorProto : global::ProtoBuf.IExtensible
	{
		
		
		public EnumDescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.EnumValueDescriptorProto> _value = new global::System.Collections.Generic.List<google.protobuf.EnumValueDescriptorProto>();
		[global::ProtoBuf.ProtoMember(2, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.EnumValueDescriptorProto> value
		{
			get { return _value; }
		}
		
		
		google.protobuf.EnumOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.EnumOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumValueDescriptorProto")]
	public partial class EnumValueDescriptorProto : global::ProtoBuf.IExtensible
	{
		
		
		public EnumValueDescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		int _number = default(int);
		bool _hasnumber = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int number
		{
			get { return _number; }
			set { _number = value; 
			      _hasnumber = true;
			}
		}
		
		public bool Hasnumber
		{
			get { return _hasnumber; }
			set { _hasnumber = value; }
		}
		
		google.protobuf.EnumValueOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.EnumValueOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServiceDescriptorProto")]
	public partial class ServiceDescriptorProto : global::ProtoBuf.IExtensible
	{
		
		
		public ServiceDescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.MethodDescriptorProto> _method = new global::System.Collections.Generic.List<google.protobuf.MethodDescriptorProto>();
		[global::ProtoBuf.ProtoMember(2, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.MethodDescriptorProto> method
		{
			get { return _method; }
		}
		
		
		google.protobuf.ServiceOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.ServiceOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MethodDescriptorProto")]
	public partial class MethodDescriptorProto : global::ProtoBuf.IExtensible
	{
		
		
		public MethodDescriptorProto() {}
		
		string _name = "";
		bool _hasname = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; 
			      _hasname = true;
			}
		}
		
		public bool Hasname
		{
			get { return _hasname; }
			set { _hasname = value; }
		}
		
		string _input_type = "";
		bool _hasinput_type = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"input_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string input_type
		{
			get { return _input_type; }
			set { _input_type = value; 
			      _hasinput_type = true;
			}
		}
		
		public bool Hasinput_type
		{
			get { return _hasinput_type; }
			set { _hasinput_type = value; }
		}
		
		string _output_type = "";
		bool _hasoutput_type = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"output_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string output_type
		{
			get { return _output_type; }
			set { _output_type = value; 
			      _hasoutput_type = true;
			}
		}
		
		public bool Hasoutput_type
		{
			get { return _hasoutput_type; }
			set { _hasoutput_type = value; }
		}
		
		google.protobuf.MethodOptions _options = null;
		bool _hasoptions = false;
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public google.protobuf.MethodOptions options
		{
			get { return _options; }
			set { _options = value; 
			      _hasoptions = true;
			}
		}
		
		public bool Hasoptions
		{
			get { return _hasoptions; }
			set { _hasoptions = value; }
		}
		
		bool _client_streaming = (bool)false;
		bool _hasclient_streaming = false;
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"client_streaming", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool client_streaming
		{
			get { return _client_streaming; }
			set { _client_streaming = value; 
			      _hasclient_streaming = true;
			}
		}
		
		public bool Hasclient_streaming
		{
			get { return _hasclient_streaming; }
			set { _hasclient_streaming = value; }
		}
		
		bool _server_streaming = (bool)false;
		bool _hasserver_streaming = false;
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"server_streaming", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool server_streaming
		{
			get { return _server_streaming; }
			set { _server_streaming = value; 
			      _hasserver_streaming = true;
			}
		}
		
		public bool Hasserver_streaming
		{
			get { return _hasserver_streaming; }
			set { _hasserver_streaming = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileOptions")]
	public partial class FileOptions : global::ProtoBuf.IExtensible
	{
		
		
		public FileOptions() {}
		
		string _java_package = "";
		bool _hasjava_package = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"java_package", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string java_package
		{
			get { return _java_package; }
			set { _java_package = value; 
			      _hasjava_package = true;
			}
		}
		
		public bool Hasjava_package
		{
			get { return _hasjava_package; }
			set { _hasjava_package = value; }
		}
		
		string _java_outer_classname = "";
		bool _hasjava_outer_classname = false;
		[global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"java_outer_classname", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string java_outer_classname
		{
			get { return _java_outer_classname; }
			set { _java_outer_classname = value; 
			      _hasjava_outer_classname = true;
			}
		}
		
		public bool Hasjava_outer_classname
		{
			get { return _hasjava_outer_classname; }
			set { _hasjava_outer_classname = value; }
		}
		
		bool _java_multiple_files = (bool)false;
		bool _hasjava_multiple_files = false;
		[global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"java_multiple_files", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool java_multiple_files
		{
			get { return _java_multiple_files; }
			set { _java_multiple_files = value; 
			      _hasjava_multiple_files = true;
			}
		}
		
		public bool Hasjava_multiple_files
		{
			get { return _hasjava_multiple_files; }
			set { _hasjava_multiple_files = value; }
		}
		
		bool _java_generate_equals_and_hash = (bool)false;
		bool _hasjava_generate_equals_and_hash = false;
		[global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"java_generate_equals_and_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool java_generate_equals_and_hash
		{
			get { return _java_generate_equals_and_hash; }
			set { _java_generate_equals_and_hash = value; 
			      _hasjava_generate_equals_and_hash = true;
			}
		}
		
		public bool Hasjava_generate_equals_and_hash
		{
			get { return _hasjava_generate_equals_and_hash; }
			set { _hasjava_generate_equals_and_hash = value; }
		}
		
		bool _java_string_check_utf8 = (bool)false;
		bool _hasjava_string_check_utf8 = false;
		[global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"java_string_check_utf8", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool java_string_check_utf8
		{
			get { return _java_string_check_utf8; }
			set { _java_string_check_utf8 = value; 
			      _hasjava_string_check_utf8 = true;
			}
		}
		
		public bool Hasjava_string_check_utf8
		{
			get { return _hasjava_string_check_utf8; }
			set { _hasjava_string_check_utf8 = value; }
		}
		
		google.protobuf.FileOptions.OptimizeMode _optimize_for = google.protobuf.FileOptions.OptimizeMode.SPEED;
		bool _hasoptimize_for = false;
		[global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"optimize_for", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(google.protobuf.FileOptions.OptimizeMode.SPEED)]
		public google.protobuf.FileOptions.OptimizeMode optimize_for
		{
			get { return _optimize_for; }
			set { _optimize_for = value; 
			      _hasoptimize_for = true;
			}
		}
		
		public bool Hasoptimize_for
		{
			get { return _hasoptimize_for; }
			set { _hasoptimize_for = value; }
		}
		
		string _go_package = "";
		bool _hasgo_package = false;
		[global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"go_package", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string go_package
		{
			get { return _go_package; }
			set { _go_package = value; 
			      _hasgo_package = true;
			}
		}
		
		public bool Hasgo_package
		{
			get { return _hasgo_package; }
			set { _hasgo_package = value; }
		}
		
		bool _cc_generic_services = (bool)false;
		bool _hascc_generic_services = false;
		[global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"cc_generic_services", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool cc_generic_services
		{
			get { return _cc_generic_services; }
			set { _cc_generic_services = value; 
			      _hascc_generic_services = true;
			}
		}
		
		public bool Hascc_generic_services
		{
			get { return _hascc_generic_services; }
			set { _hascc_generic_services = value; }
		}
		
		bool _java_generic_services = (bool)false;
		bool _hasjava_generic_services = false;
		[global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"java_generic_services", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool java_generic_services
		{
			get { return _java_generic_services; }
			set { _java_generic_services = value; 
			      _hasjava_generic_services = true;
			}
		}
		
		public bool Hasjava_generic_services
		{
			get { return _hasjava_generic_services; }
			set { _hasjava_generic_services = value; }
		}
		
		bool _py_generic_services = (bool)false;
		bool _haspy_generic_services = false;
		[global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"py_generic_services", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool py_generic_services
		{
			get { return _py_generic_services; }
			set { _py_generic_services = value; 
			      _haspy_generic_services = true;
			}
		}
		
		public bool Haspy_generic_services
		{
			get { return _haspy_generic_services; }
			set { _haspy_generic_services = value; }
		}
		
		bool _deprecated = (bool)false;
		bool _hasdeprecated = false;
		[global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool deprecated
		{
			get { return _deprecated; }
			set { _deprecated = value; 
			      _hasdeprecated = true;
			}
		}
		
		public bool Hasdeprecated
		{
			get { return _hasdeprecated; }
			set { _hasdeprecated = value; }
		}
		
		bool _cc_enable_arenas = (bool)false;
		bool _hascc_enable_arenas = false;
		[global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"cc_enable_arenas", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool cc_enable_arenas
		{
			get { return _cc_enable_arenas; }
			set { _cc_enable_arenas = value; 
			      _hascc_enable_arenas = true;
			}
		}
		
		public bool Hascc_enable_arenas
		{
			get { return _hascc_enable_arenas; }
			set { _hascc_enable_arenas = value; }
		}
		
		string _objc_class_prefix = "";
		bool _hasobjc_class_prefix = false;
		[global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"objc_class_prefix", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string objc_class_prefix
		{
			get { return _objc_class_prefix; }
			set { _objc_class_prefix = value; 
			      _hasobjc_class_prefix = true;
			}
		}
		
		public bool Hasobjc_class_prefix
		{
			get { return _hasobjc_class_prefix; }
			set { _hasobjc_class_prefix = value; }
		}
		
		string _csharp_namespace = "";
		bool _hascsharp_namespace = false;
		[global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"csharp_namespace", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string csharp_namespace
		{
			get { return _csharp_namespace; }
			set { _csharp_namespace = value; 
			      _hascsharp_namespace = true;
			}
		}
		
		public bool Hascsharp_namespace
		{
			get { return _hascsharp_namespace; }
			set { _hascsharp_namespace = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		[global::ProtoBuf.ProtoContract(Name=@"OptimizeMode")]
		public enum OptimizeMode
		{
			[global::ProtoBuf.ProtoEnum(Name=@"SPEED", Value=1)]
			SPEED = 1,
			
			[global::ProtoBuf.ProtoEnum(Name=@"CODE_SIZE", Value=2)]
			CODE_SIZE = 2,
			
			[global::ProtoBuf.ProtoEnum(Name=@"LITE_RUNTIME", Value=3)]
			LITE_RUNTIME = 3
			
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageOptions")]
	public partial class MessageOptions : global::ProtoBuf.IExtensible
	{
		
		
		public MessageOptions() {}
		
		bool _message_set_wire_format = (bool)false;
		bool _hasmessage_set_wire_format = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_set_wire_format", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool message_set_wire_format
		{
			get { return _message_set_wire_format; }
			set { _message_set_wire_format = value; 
			      _hasmessage_set_wire_format = true;
			}
		}
		
		public bool Hasmessage_set_wire_format
		{
			get { return _hasmessage_set_wire_format; }
			set { _hasmessage_set_wire_format = value; }
		}
		
		bool _no_standard_descriptor_accessor = (bool)false;
		bool _hasno_standard_descriptor_accessor = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"no_standard_descriptor_accessor", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool no_standard_descriptor_accessor
		{
			get { return _no_standard_descriptor_accessor; }
			set { _no_standard_descriptor_accessor = value; 
			      _hasno_standard_descriptor_accessor = true;
			}
		}
		
		public bool Hasno_standard_descriptor_accessor
		{
			get { return _hasno_standard_descriptor_accessor; }
			set { _hasno_standard_descriptor_accessor = value; }
		}
		
		bool _deprecated = (bool)false;
		bool _hasdeprecated = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool deprecated
		{
			get { return _deprecated; }
			set { _deprecated = value; 
			      _hasdeprecated = true;
			}
		}
		
		public bool Hasdeprecated
		{
			get { return _hasdeprecated; }
			set { _hasdeprecated = value; }
		}
		
		bool _map_entry = default(bool);
		bool _hasmap_entry = false;
		[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"map_entry", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool map_entry
		{
			get { return _map_entry; }
			set { _map_entry = value; 
			      _hasmap_entry = true;
			}
		}
		
		public bool Hasmap_entry
		{
			get { return _hasmap_entry; }
			set { _hasmap_entry = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FieldOptions")]
	public partial class FieldOptions : global::ProtoBuf.IExtensible
	{
		
		
		public FieldOptions() {}
		
		google.protobuf.FieldOptions.CType _ctype = google.protobuf.FieldOptions.CType.STRING;
		bool _hasctype = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ctype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(google.protobuf.FieldOptions.CType.STRING)]
		public google.protobuf.FieldOptions.CType ctype
		{
			get { return _ctype; }
			set { _ctype = value; 
			      _hasctype = true;
			}
		}
		
		public bool Hasctype
		{
			get { return _hasctype; }
			set { _hasctype = value; }
		}
		
		bool _packed = default(bool);
		bool _haspacked = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"packed", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool packed
		{
			get { return _packed; }
			set { _packed = value; 
			      _haspacked = true;
			}
		}
		
		public bool Haspacked
		{
			get { return _haspacked; }
			set { _haspacked = value; }
		}
		
		google.protobuf.FieldOptions.JSType _jstype = google.protobuf.FieldOptions.JSType.JS_NORMAL;
		bool _hasjstype = false;
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"jstype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(google.protobuf.FieldOptions.JSType.JS_NORMAL)]
		public google.protobuf.FieldOptions.JSType jstype
		{
			get { return _jstype; }
			set { _jstype = value; 
			      _hasjstype = true;
			}
		}
		
		public bool Hasjstype
		{
			get { return _hasjstype; }
			set { _hasjstype = value; }
		}
		
		bool _lazy = (bool)false;
		bool _haslazy = false;
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lazy", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool lazy
		{
			get { return _lazy; }
			set { _lazy = value; 
			      _haslazy = true;
			}
		}
		
		public bool Haslazy
		{
			get { return _haslazy; }
			set { _haslazy = value; }
		}
		
		bool _deprecated = (bool)false;
		bool _hasdeprecated = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool deprecated
		{
			get { return _deprecated; }
			set { _deprecated = value; 
			      _hasdeprecated = true;
			}
		}
		
		public bool Hasdeprecated
		{
			get { return _hasdeprecated; }
			set { _hasdeprecated = value; }
		}
		
		bool _weak = (bool)false;
		bool _hasweak = false;
		[global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"weak", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool weak
		{
			get { return _weak; }
			set { _weak = value; 
			      _hasweak = true;
			}
		}
		
		public bool Hasweak
		{
			get { return _hasweak; }
			set { _hasweak = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		[global::ProtoBuf.ProtoContract(Name=@"CType")]
		public enum CType
		{
			[global::ProtoBuf.ProtoEnum(Name=@"STRING", Value=0)]
			STRING = 0,
			
			[global::ProtoBuf.ProtoEnum(Name=@"CORD", Value=1)]
			CORD = 1,
			
			[global::ProtoBuf.ProtoEnum(Name=@"STRING_PIECE", Value=2)]
			STRING_PIECE = 2
			
		}
		[global::ProtoBuf.ProtoContract(Name=@"JSType")]
		public enum JSType
		{
			[global::ProtoBuf.ProtoEnum(Name=@"JS_NORMAL", Value=0)]
			JS_NORMAL = 0,
			
			[global::ProtoBuf.ProtoEnum(Name=@"JS_STRING", Value=1)]
			JS_STRING = 1,
			
			[global::ProtoBuf.ProtoEnum(Name=@"JS_NUMBER", Value=2)]
			JS_NUMBER = 2
			
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneofOptions")]
	public partial class OneofOptions : global::ProtoBuf.IExtensible
	{
		
		
		public OneofOptions() {}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumOptions")]
	public partial class EnumOptions : global::ProtoBuf.IExtensible
	{
		
		
		public EnumOptions() {}
		
		bool _allow_alias = default(bool);
		bool _hasallow_alias = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"allow_alias", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool allow_alias
		{
			get { return _allow_alias; }
			set { _allow_alias = value; 
			      _hasallow_alias = true;
			}
		}
		
		public bool Hasallow_alias
		{
			get { return _hasallow_alias; }
			set { _hasallow_alias = value; }
		}
		
		bool _deprecated = (bool)false;
		bool _hasdeprecated = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool deprecated
		{
			get { return _deprecated; }
			set { _deprecated = value; 
			      _hasdeprecated = true;
			}
		}
		
		public bool Hasdeprecated
		{
			get { return _hasdeprecated; }
			set { _hasdeprecated = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumValueOptions")]
	public partial class EnumValueOptions : global::ProtoBuf.IExtensible
	{
		
		
		public EnumValueOptions() {}
		
		bool _deprecated = (bool)false;
		bool _hasdeprecated = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool deprecated
		{
			get { return _deprecated; }
			set { _deprecated = value; 
			      _hasdeprecated = true;
			}
		}
		
		public bool Hasdeprecated
		{
			get { return _hasdeprecated; }
			set { _hasdeprecated = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServiceOptions")]
	public partial class ServiceOptions : global::ProtoBuf.IExtensible
	{
		
		
		public ServiceOptions() {}
		
		bool _deprecated = (bool)false;
		bool _hasdeprecated = false;
		[global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool deprecated
		{
			get { return _deprecated; }
			set { _deprecated = value; 
			      _hasdeprecated = true;
			}
		}
		
		public bool Hasdeprecated
		{
			get { return _hasdeprecated; }
			set { _hasdeprecated = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MethodOptions")]
	public partial class MethodOptions : global::ProtoBuf.IExtensible
	{
		
		
		public MethodOptions() {}
		
		bool _deprecated = (bool)false;
		bool _hasdeprecated = false;
		[global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue((bool)false)]
		public bool deprecated
		{
			get { return _deprecated; }
			set { _deprecated = value; 
			      _hasdeprecated = true;
			}
		}
		
		public bool Hasdeprecated
		{
			get { return _hasdeprecated; }
			set { _hasdeprecated = value; }
		}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
		[global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
		{
			get { return _uninterpreted_option; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UninterpretedOption")]
	public partial class UninterpretedOption : global::ProtoBuf.IExtensible
	{
		
		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NamePart")]
		public partial class NamePart : global::ProtoBuf.IExtensible
		{
			
			
			public NamePart() {}
			
			string _name_part = "";
			bool _hasname_part = false;
			[global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name_part", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue("")]
			public string name_part
			{
				get { return _name_part; }
				set { _name_part = value; 
				      _hasname_part = true;
				}
			}
			
			public bool Hasname_part
			{
				get { return _hasname_part; }
				set { _hasname_part = value; }
			}
			
			bool _is_extension = default(bool);
			bool _hasis_extension = false;
			[global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue(default(bool))]
			public bool is_extension
			{
				get { return _is_extension; }
				set { _is_extension = value; 
				      _hasis_extension = true;
				}
			}
			
			public bool Hasis_extension
			{
				get { return _hasis_extension; }
				set { _hasis_extension = value; }
			}
			
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}
		
		public UninterpretedOption() {}
		
		readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption.NamePart> _name = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption.NamePart>();
		[global::ProtoBuf.ProtoMember(2, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption.NamePart> name
		{
			get { return _name; }
		}
		
		
		string _identifier_value = "";
		bool _hasidentifier_value = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"identifier_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string identifier_value
		{
			get { return _identifier_value; }
			set { _identifier_value = value; 
			      _hasidentifier_value = true;
			}
		}
		
		public bool Hasidentifier_value
		{
			get { return _hasidentifier_value; }
			set { _hasidentifier_value = value; }
		}
		
		ulong _positive_int_value = default(ulong);
		bool _haspositive_int_value = false;
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"positive_int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(ulong))]
		public ulong positive_int_value
		{
			get { return _positive_int_value; }
			set { _positive_int_value = value; 
			      _haspositive_int_value = true;
			}
		}
		
		public bool Haspositive_int_value
		{
			get { return _haspositive_int_value; }
			set { _haspositive_int_value = value; }
		}
		
		long _negative_int_value = default(long);
		bool _hasnegative_int_value = false;
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"negative_int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(long))]
		public long negative_int_value
		{
			get { return _negative_int_value; }
			set { _negative_int_value = value; 
			      _hasnegative_int_value = true;
			}
		}
		
		public bool Hasnegative_int_value
		{
			get { return _hasnegative_int_value; }
			set { _hasnegative_int_value = value; }
		}
		
		double _double_value = default(double);
		bool _hasdouble_value = false;
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"double_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(double))]
		public double double_value
		{
			get { return _double_value; }
			set { _double_value = value; 
			      _hasdouble_value = true;
			}
		}
		
		public bool Hasdouble_value
		{
			get { return _hasdouble_value; }
			set { _hasdouble_value = value; }
		}
		
		byte[] _string_value = default(byte[]);
		bool _hasstring_value = false;
		[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"string_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(byte[]))]
		public byte[] string_value
		{
			get { return _string_value; }
			set { _string_value = value; 
			      _hasstring_value = true;
			}
		}
		
		public bool Hasstring_value
		{
			get { return _hasstring_value; }
			set { _hasstring_value = value; }
		}
		
		string _aggregate_value = "";
		bool _hasaggregate_value = false;
		[global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"aggregate_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string aggregate_value
		{
			get { return _aggregate_value; }
			set { _aggregate_value = value; 
			      _hasaggregate_value = true;
			}
		}
		
		public bool Hasaggregate_value
		{
			get { return _hasaggregate_value; }
			set { _hasaggregate_value = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SourceCodeInfo")]
	public partial class SourceCodeInfo : global::ProtoBuf.IExtensible
	{
		
		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Location")]
		public partial class Location : global::ProtoBuf.IExtensible
		{
			
			
			public Location() {}
			
			readonly global::System.Collections.Generic.List<int> _path = new global::System.Collections.Generic.List<int>();
			[global::ProtoBuf.ProtoMember(1, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			public global::System.Collections.Generic.List<int> path
			{
				get { return _path; }
			}
			
			
			readonly global::System.Collections.Generic.List<int> _span = new global::System.Collections.Generic.List<int>();
			[global::ProtoBuf.ProtoMember(2, Name=@"span", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			public global::System.Collections.Generic.List<int> span
			{
				get { return _span; }
			}
			
			
			string _leading_comments = "";
			bool _hasleading_comments = false;
			[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leading_comments", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue("")]
			public string leading_comments
			{
				get { return _leading_comments; }
				set { _leading_comments = value; 
				      _hasleading_comments = true;
				}
			}
			
			public bool Hasleading_comments
			{
				get { return _hasleading_comments; }
				set { _hasleading_comments = value; }
			}
			
			string _trailing_comments = "";
			bool _hastrailing_comments = false;
			[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"trailing_comments", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue("")]
			public string trailing_comments
			{
				get { return _trailing_comments; }
				set { _trailing_comments = value; 
				      _hastrailing_comments = true;
				}
			}
			
			public bool Hastrailing_comments
			{
				get { return _hastrailing_comments; }
				set { _hastrailing_comments = value; }
			}
			
			readonly global::System.Collections.Generic.List<string> _leading_detached_comments = new global::System.Collections.Generic.List<string>();
			[global::ProtoBuf.ProtoMember(6, Name=@"leading_detached_comments", DataFormat = global::ProtoBuf.DataFormat.Default)]
			public global::System.Collections.Generic.List<string> leading_detached_comments
			{
				get { return _leading_detached_comments; }
			}
			
			
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}
		
		public SourceCodeInfo() {}
		
		readonly global::System.Collections.Generic.List<google.protobuf.SourceCodeInfo.Location> _location = new global::System.Collections.Generic.List<google.protobuf.SourceCodeInfo.Location>();
		[global::ProtoBuf.ProtoMember(1, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.SourceCodeInfo.Location> location
		{
			get { return _location; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GeneratedCodeInfo")]
	public partial class GeneratedCodeInfo : global::ProtoBuf.IExtensible
	{
		
		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Annotation")]
		public partial class Annotation : global::ProtoBuf.IExtensible
		{
			
			
			public Annotation() {}
			
			readonly global::System.Collections.Generic.List<int> _path = new global::System.Collections.Generic.List<int>();
			[global::ProtoBuf.ProtoMember(1, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			public global::System.Collections.Generic.List<int> path
			{
				get { return _path; }
			}
			
			
			string _source_file = "";
			bool _hassource_file = false;
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"source_file", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue("")]
			public string source_file
			{
				get { return _source_file; }
				set { _source_file = value; 
				      _hassource_file = true;
				}
			}
			
			public bool Hassource_file
			{
				get { return _hassource_file; }
				set { _hassource_file = value; }
			}
			
			int _begin = default(int);
			bool _hasbegin = false;
			[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"begin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int begin
			{
				get { return _begin; }
				set { _begin = value; 
				      _hasbegin = true;
				}
			}
			
			public bool Hasbegin
			{
				get { return _hasbegin; }
				set { _hasbegin = value; }
			}
			
			int _end = default(int);
			bool _hasend = false;
			[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int end
			{
				get { return _end; }
				set { _end = value; 
				      _hasend = true;
				}
			}
			
			public bool Hasend
			{
				get { return _hasend; }
				set { _hasend = value; }
			}
			
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}
		
		public GeneratedCodeInfo() {}
		
		readonly global::System.Collections.Generic.List<google.protobuf.GeneratedCodeInfo.Annotation> _annotation = new global::System.Collections.Generic.List<google.protobuf.GeneratedCodeInfo.Annotation>();
		[global::ProtoBuf.ProtoMember(1, Name=@"annotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<google.protobuf.GeneratedCodeInfo.Annotation> annotation
		{
			get { return _annotation; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
