// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: framework.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CodeGenPeer")]
	public partial class CodeGenPeer : global::ProtoBuf.IExtensible
	{
		public CodeGenPeer() {}
		
		string _Name = "";
		bool _hasName = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; 
			      _hasName = true;
			}
		}
		
		public bool HasName
		{
			get { return _hasName; }
			set { _hasName = value; }
		}
		
		readonly global::System.Collections.Generic.List<string> _RecvMessage = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(2, Name=@"RecvMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> RecvMessage
		{
			get { return _RecvMessage; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CodeGenModule")]
	public partial class CodeGenModule : global::ProtoBuf.IExtensible
	{
		public CodeGenModule() {}
		
		string _Name = "";
		bool _hasName = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; 
			      _hasName = true;
			}
		}
		
		public bool HasName
		{
			get { return _hasName; }
			set { _hasName = value; }
		}
		
		readonly global::System.Collections.Generic.List<gamedef.CodeGenPeer> _Peer = new global::System.Collections.Generic.List<gamedef.CodeGenPeer>();
		[global::ProtoBuf.ProtoMember(2, Name=@"Peer", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.CodeGenPeer> Peer
		{
			get { return _Peer; }
		}
		
		
		gamedef.ModelGenType _ModelGen = gamedef.ModelGenType.MGT_Singleton;
		bool _hasModelGen = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ModelGen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.ModelGenType.MGT_Singleton)]
		public gamedef.ModelGenType ModelGen
		{
			get { return _ModelGen; }
			set { _ModelGen = value; 
			      _hasModelGen = true;
			}
		}
		
		public bool HasModelGen
		{
			get { return _hasModelGen; }
			set { _hasModelGen = value; }
		}
		
		bool _NoGenPresenterCode = default(bool);
		bool _hasNoGenPresenterCode = false;
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"NoGenPresenterCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool NoGenPresenterCode
		{
			get { return _NoGenPresenterCode; }
			set { _NoGenPresenterCode = value; 
			      _hasNoGenPresenterCode = true;
			}
		}
		
		public bool HasNoGenPresenterCode
		{
			get { return _hasNoGenPresenterCode; }
			set { _hasNoGenPresenterCode = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CodeGenFile")]
	public partial class CodeGenFile : global::ProtoBuf.IExtensible
	{
		public CodeGenFile() {}
		
		readonly global::System.Collections.Generic.List<gamedef.CodeGenModule> _CodeGen = new global::System.Collections.Generic.List<gamedef.CodeGenModule>();
		[global::ProtoBuf.ProtoMember(1, Name=@"CodeGen", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.CodeGenModule> CodeGen
		{
			get { return _CodeGen; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestProfile")]
	public partial class TestProfile : global::ProtoBuf.IExtensible
	{
		public TestProfile() {}
		
		int _HP = default(int);
		bool _hasHP = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int HP
		{
			get { return _HP; }
			set { _HP = value; 
			      _hasHP = true;
			}
		}
		
		public bool HasHP
		{
			get { return _hasHP; }
			set { _hasHP = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestBag")]
	public partial class TestBag : global::ProtoBuf.IExtensible
	{
		public TestBag() {}
		
		uint _ID = default(uint);
		bool _hasID = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(uint))]
		public uint ID
		{
			get { return _ID; }
			set { _ID = value; 
			      _hasID = true;
			}
		}
		
		public bool HasID
		{
			get { return _hasID; }
			set { _hasID = value; }
		}
		
		string _Name = "";
		bool _hasName = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; 
			      _hasName = true;
			}
		}
		
		public bool HasName
		{
			get { return _hasName; }
			set { _hasName = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestProfileSyncACK")]
	public partial class TestProfileSyncACK : global::ProtoBuf.IExtensible
	{
		public TestProfileSyncACK() {}
		
		gamedef.TestProfile _Profile = null;
		bool _hasProfile = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Profile", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public gamedef.TestProfile Profile
		{
			get { return _Profile; }
			set { _Profile = value; 
			      _hasProfile = true;
			}
		}
		
		public bool HasProfile
		{
			get { return _hasProfile; }
			set { _hasProfile = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestBagSyncACK")]
	public partial class TestBagSyncACK : global::ProtoBuf.IExtensible
	{
		public TestBagSyncACK() {}
		
		readonly global::System.Collections.Generic.List<gamedef.TestBag> _Bag_Add = new global::System.Collections.Generic.List<gamedef.TestBag>();
		[global::ProtoBuf.ProtoMember(1, Name=@"Bag_Add", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.TestBag> Bag_Add
		{
			get { return _Bag_Add; }
		}
		
		
		readonly global::System.Collections.Generic.List<uint> _Bag_Delete = new global::System.Collections.Generic.List<uint>();
		[global::ProtoBuf.ProtoMember(2, Name=@"Bag_Delete", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public global::System.Collections.Generic.List<uint> Bag_Delete
		{
			get { return _Bag_Delete; }
		}
		
		
		readonly global::System.Collections.Generic.List<gamedef.TestBag> _Bag_Set = new global::System.Collections.Generic.List<gamedef.TestBag>();
		[global::ProtoBuf.ProtoMember(3, Name=@"Bag_Set", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.TestBag> Bag_Set
		{
			get { return _Bag_Set; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
	[global::ProtoBuf.ProtoContract(Name=@"ModelGenType")]
	public enum ModelGenType
	{
		[global::ProtoBuf.ProtoEnum(Name=@"MGT_Singleton", Value=0)]
		MGT_Singleton = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"MGT_Instance", Value=1)]
		MGT_Instance = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"MGT_Manual", Value=2)]
		MGT_Manual = 2
		
	}
}
