// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: framework.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CodeGenPeer")]
	public partial class CodeGenPeer : global::ProtoBuf.IExtensible
	{
		public CodeGenPeer() {}
		
		private string _Name = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; }
		}
		
		private readonly global::System.Collections.Generic.List<string> _RecvMessage = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(2, Name=@"RecvMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> RecvMessage
		{
			get { return _RecvMessage; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CodeGenModule")]
	public partial class CodeGenModule : global::ProtoBuf.IExtensible
	{
		public CodeGenModule() {}
		
		private string _Name = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; }
		}
		
		private readonly global::System.Collections.Generic.List<gamedef.CodeGenPeer> _Peer = new global::System.Collections.Generic.List<gamedef.CodeGenPeer>();
		[global::ProtoBuf.ProtoMember(2, Name=@"Peer", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.CodeGenPeer> Peer
		{
			get { return _Peer; }
		}
		
		private gamedef.ModelGenType _ModelGen = gamedef.ModelGenType.MGT_Singleton;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ModelGen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.ModelGenType.MGT_Singleton)]
		public gamedef.ModelGenType ModelGen
		{
			get { return _ModelGen; }
			set { _ModelGen = value; }
		}
		
		private bool _NoGenPresenterCode = default(bool);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"NoGenPresenterCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool NoGenPresenterCode
		{
			get { return _NoGenPresenterCode; }
			set { _NoGenPresenterCode = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CodeGenFile")]
	public partial class CodeGenFile : global::ProtoBuf.IExtensible
	{
		public CodeGenFile() {}
		
		private readonly global::System.Collections.Generic.List<gamedef.CodeGenModule> _CodeGen = new global::System.Collections.Generic.List<gamedef.CodeGenModule>();
		[global::ProtoBuf.ProtoMember(1, Name=@"CodeGen", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.CodeGenModule> CodeGen
		{
			get { return _CodeGen; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModelDataPair")]
	public partial class ModelDataPair : global::ProtoBuf.IExtensible
	{
		public ModelDataPair() {}
		
		private uint _KeyID = default(uint);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"KeyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(uint))]
		public uint KeyID
		{
			get { return _KeyID; }
			set { _KeyID = value; }
		}
		
		private string _KeyStr = "";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"KeyStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string KeyStr
		{
			get { return _KeyStr; }
			set { _KeyStr = value; }
		}
		
		private int _Integer = default(int);
		[global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Integer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int Integer
		{
			get { return _Integer; }
			set { _Integer = value; }
		}
		
		private string _Str = "";
		[global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Str", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Str
		{
			get { return _Str; }
			set { _Str = value; }
		}
		
		private float _Number = default(float);
		[global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"Number", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float Number
		{
			get { return _Number; }
			set { _Number = value; }
		}
		
		private bool _Bool = default(bool);
		[global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Bool", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool Bool
		{
			get { return _Bool; }
			set { _Bool = value; }
		}
		
		private gamedef.ModelSyncBehavior _SyncBehavior = gamedef.ModelSyncBehavior.MSB_None;
		[global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"SyncBehavior", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.ModelSyncBehavior.MSB_None)]
		public gamedef.ModelSyncBehavior SyncBehavior
		{
			get { return _SyncBehavior; }
			set { _SyncBehavior = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModelDataACK")]
	public partial class ModelDataACK : global::ProtoBuf.IExtensible
	{
		public ModelDataACK() {}
		
		private readonly global::System.Collections.Generic.List<gamedef.ModelDataPair> _Data = new global::System.Collections.Generic.List<gamedef.ModelDataPair>();
		[global::ProtoBuf.ProtoMember(1, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.ModelDataPair> Data
		{
			get { return _Data; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
	[global::ProtoBuf.ProtoContract(Name=@"ModelGenType")]
	public enum ModelGenType
	{
		[global::ProtoBuf.ProtoEnum(Name=@"MGT_Singleton", Value=0)]
		MGT_Singleton = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"MGT_Instance", Value=1)]
		MGT_Instance = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"MGT_Manual", Value=2)]
		MGT_Manual = 2
		
	}
	[global::ProtoBuf.ProtoContract(Name=@"ModelSyncBehavior")]
	public enum ModelSyncBehavior
	{
		[global::ProtoBuf.ProtoEnum(Name=@"MSB_None", Value=0)]
		MSB_None = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"MSB_Modified", Value=1)]
		MSB_Modified = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"MSB_Added", Value=2)]
		MSB_Added = 2,
		
		[global::ProtoBuf.ProtoEnum(Name=@"MSB_Removed", Value=3)]
		MSB_Removed = 3
		
	}
}
