// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: game.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyGameREQ")]
	public partial class VerifyGameREQ : global::ProtoBuf.IExtensible
	{
		public VerifyGameREQ() {}
		
		string _Token = "";
		bool _hasToken = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Token
		{
			get { return _Token; }
			set { _Token = value; 
			      _hasToken = true;
			}
		}
		
		public bool HasToken
		{
			get { return _hasToken; }
			set { _hasToken = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyGameACK")]
	public partial class VerifyGameACK : global::ProtoBuf.IExtensible
	{
		public VerifyGameACK() {}
		
		gamedef.VerifyGameResult _Result = gamedef.VerifyGameResult.VerifyOK;
		bool _hasResult = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.VerifyGameResult.VerifyOK)]
		public gamedef.VerifyGameResult Result
		{
			get { return _Result; }
			set { _Result = value; 
			      _hasResult = true;
			}
		}
		
		public bool HasResult
		{
			get { return _hasResult; }
			set { _hasResult = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimpleCharInfo")]
	public partial class SimpleCharInfo : global::ProtoBuf.IExtensible
	{
		public SimpleCharInfo() {}
		
		string _CharName = "";
		bool _hasCharName = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharName", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string CharName
		{
			get { return _CharName; }
			set { _CharName = value; 
			      _hasCharName = true;
			}
		}
		
		public bool HasCharName
		{
			get { return _hasCharName; }
			set { _hasCharName = value; }
		}
		
		long _LastLoginUTC = default(long);
		bool _hasLastLoginUTC = false;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LastLoginUTC", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(long))]
		public long LastLoginUTC
		{
			get { return _LastLoginUTC; }
			set { _LastLoginUTC = value; 
			      _hasLastLoginUTC = true;
			}
		}
		
		public bool HasLastLoginUTC
		{
			get { return _hasLastLoginUTC; }
			set { _hasLastLoginUTC = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharListREQ")]
	public partial class CharListREQ : global::ProtoBuf.IExtensible
	{
		public CharListREQ() {}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharListACK")]
	public partial class CharListACK : global::ProtoBuf.IExtensible
	{
		public CharListACK() {}
		
		readonly global::System.Collections.Generic.List<gamedef.SimpleCharInfo> _CharInfo = new global::System.Collections.Generic.List<gamedef.SimpleCharInfo>();
		[global::ProtoBuf.ProtoMember(1, Name=@"CharInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.SimpleCharInfo> CharInfo
		{
			get { return _CharInfo; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateCharREQ")]
	public partial class CreateCharREQ : global::ProtoBuf.IExtensible
	{
		public CreateCharREQ() {}
		
		int _CandidateID = default(int);
		bool _hasCandidateID = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CandidateID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int CandidateID
		{
			get { return _CandidateID; }
			set { _CandidateID = value; 
			      _hasCandidateID = true;
			}
		}
		
		public bool HasCandidateID
		{
			get { return _hasCandidateID; }
			set { _hasCandidateID = value; }
		}
		
		string _CharName = "";
		bool _hasCharName = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharName", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string CharName
		{
			get { return _CharName; }
			set { _CharName = value; 
			      _hasCharName = true;
			}
		}
		
		public bool HasCharName
		{
			get { return _hasCharName; }
			set { _hasCharName = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateCharACK")]
	public partial class CreateCharACK : global::ProtoBuf.IExtensible
	{
		public CreateCharACK() {}
		
		int _CandidateID = default(int);
		bool _hasCandidateID = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CandidateID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int CandidateID
		{
			get { return _CandidateID; }
			set { _CandidateID = value; 
			      _hasCandidateID = true;
			}
		}
		
		public bool HasCandidateID
		{
			get { return _hasCandidateID; }
			set { _hasCandidateID = value; }
		}
		
		gamedef.CreateCharResult _Result = gamedef.CreateCharResult.CreateCharOK;
		bool _hasResult = false;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.CreateCharResult.CreateCharOK)]
		public gamedef.CreateCharResult Result
		{
			get { return _Result; }
			set { _Result = value; 
			      _hasResult = true;
			}
		}
		
		public bool HasResult
		{
			get { return _hasResult; }
			set { _hasResult = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameREQ")]
	public partial class EnterGameREQ : global::ProtoBuf.IExtensible
	{
		public EnterGameREQ() {}
		
		string _CharName = "";
		bool _hasCharName = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharName", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string CharName
		{
			get { return _CharName; }
			set { _CharName = value; 
			      _hasCharName = true;
			}
		}
		
		public bool HasCharName
		{
			get { return _hasCharName; }
			set { _hasCharName = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameACK")]
	public partial class EnterGameACK : global::ProtoBuf.IExtensible
	{
		public EnterGameACK() {}
		
		gamedef.EnterGameResult _Result = gamedef.EnterGameResult.EnterGameOK;
		bool _hasResult = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.EnterGameResult.EnterGameOK)]
		public gamedef.EnterGameResult Result
		{
			get { return _Result; }
			set { _Result = value; 
			      _hasResult = true;
			}
		}
		
		public bool HasResult
		{
			get { return _hasResult; }
			set { _hasResult = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
	[global::ProtoBuf.ProtoContract(Name=@"VerifyGameResult")]
	public enum VerifyGameResult
	{
		[global::ProtoBuf.ProtoEnum(Name=@"VerifyOK", Value=0)]
		VerifyOK = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"DataException", Value=1)]
		DataException = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"AccountBlocked", Value=2)]
		AccountBlocked = 2
		
	}
	[global::ProtoBuf.ProtoContract(Name=@"CreateCharResult")]
	public enum CreateCharResult
	{
		[global::ProtoBuf.ProtoEnum(Name=@"CreateCharOK", Value=0)]
		CreateCharOK = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"CharNotExist", Value=1)]
		CharNotExist = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"CreateCharError", Value=2)]
		CreateCharError = 2
		
	}
	[global::ProtoBuf.ProtoContract(Name=@"EnterGameResult")]
	public enum EnterGameResult
	{
		[global::ProtoBuf.ProtoEnum(Name=@"EnterGameOK", Value=0)]
		EnterGameOK = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"GameUserFull", Value=1)]
		GameUserFull = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"CharBlocked", Value=2)]
		CharBlocked = 2
		
	}
}
