// This code is generated by github.com/davyxu/protoc-gen-sharpnet, DO NOT EDIT
// Generated from: game.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameREQ")]
	public partial class EnterGameREQ : global::ProtoBuf.IExtensible
	{
		public EnterGameREQ() {}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameACK")]
	public partial class EnterGameACK : global::ProtoBuf.IExtensible
	{
		public EnterGameACK() {}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
