// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: login.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginREQ")]
	public partial class LoginREQ : global::ProtoBuf.IExtensible
	{
		public LoginREQ() {}
		
		private string _PlatformToken = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlatformToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string PlatformToken
		{
			get { return _PlatformToken; }
			set { _PlatformToken = value; }
		}
		
		private string _PlatformUID = "";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PlatformUID", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string PlatformUID
		{
			get { return _PlatformUID; }
			set { _PlatformUID = value; }
		}
		
		private string _PlatformName = "";
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PlatformName", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string PlatformName
		{
			get { return _PlatformName; }
			set { _PlatformName = value; }
		}
		
		private string _ClientVersion = "";
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ClientVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string ClientVersion
		{
			get { return _ClientVersion; }
			set { _ClientVersion = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfo")]
	public partial class ServerInfo : global::ProtoBuf.IExtensible
	{
		public ServerInfo() {}
		
		private string _Name = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; }
		}
		
		private string _DisplayName = "";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DisplayName", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string DisplayName
		{
			get { return _DisplayName; }
			set { _DisplayName = value; }
		}
		
		private string _Address = "";
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Address
		{
			get { return _Address; }
			set { _Address = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginACK")]
	public partial class LoginACK : global::ProtoBuf.IExtensible
	{
		public LoginACK() {}
		
		private string _Result = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Result
		{
			get { return _Result; }
			set { _Result = value; }
		}
		
		private string _Token = "";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Token
		{
			get { return _Token; }
			set { _Token = value; }
		}
		
		private readonly global::System.Collections.Generic.List<gamedef.ServerInfo> _ServerList = new global::System.Collections.Generic.List<gamedef.ServerInfo>();
		[global::ProtoBuf.ProtoMember(3, Name=@"ServerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.ServerInfo> ServerList
		{
			get { return _ServerList; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
