// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: model.proto
	// login.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModelOverrideACK")]
	public partial class ModelOverrideACK : global::ProtoBuf.IExtensible
	{
		
		
		public ModelOverrideACK() {}
		
		readonly global::System.Collections.Generic.List<gamedef.ServerInfo> _ServerList = new global::System.Collections.Generic.List<gamedef.ServerInfo>();
		[global::ProtoBuf.ProtoMember(1, Name=@"ServerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<gamedef.ServerInfo> ServerList
		{
			get { return _ServerList; }
		}
		
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
