// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: network.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PeerConnected")]
	public partial class PeerConnected : global::ProtoBuf.IExtensible
	{
		public PeerConnected() {}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PeerClosed")]
	public partial class PeerClosed : global::ProtoBuf.IExtensible
	{
		public PeerClosed() {}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
