// Generated by github.com/davyxu/cellorigin
using UnityEngine;
using UnityEngine.UI;
using System;


partial class TestBoardPresenter : Framework.BasePresenter
{
    public TestBoardPresenter()
	{
        Init();
	}

    void Msg_game_TestProfileSyncACK(NetworkPeer peer, gamedef.TestProfileSyncACK msg )
    {
        
    }


    void Msg_game_TestBagSyncACK(NetworkPeer peer, gamedef.TestBagSyncACK msg)
    {

    }
}
