// Generated by github.com/davyxu/cellorigin
using UnityEngine;
using UnityEngine.UI;
using System;


partial class TestBoardPresenter : Framework.BasePresenter
{
    public TestBoardPresenter()
	{
        Init();
	}


}
