// Generated by github.com/davyxu/cellorigin
using UnityEngine;
using UnityEngine.UI;
using System;

partial class LoginCharInfoPresenter : Framework.BasePresenter
{
	LoginCharInfoModel _Model;
	
	public Action OnCharNameChanged;
	public string CharName
	{
		get
		{
			return _Model.CharName;
		}
		set
		{
			_Model.CharName = value;
			
			if ( OnCharNameChanged != null )
			{
				OnCharNameChanged();
			}
		}
	}
	
	public void Init( )
	{
		_Model = new LoginCharInfoModel();
		
	}
	
}
