// Generated by github.com/cellorigin/tool/protoc-gen-table
// DO NOT EDIT!
// Source: behavior.proto
package table

import (
	"proto/gamedef"
	"share"
)

var BehaviorByID = make(map[int32]*gamedef.BehaviorDefine)

var behaviorFile gamedef.BehaviorFile

func LoadBehaviorTable() {

	log.Infoln("load behavior table...")
	
	if share.LoadTable("Behavior", &behaviorFile) != nil {
		return
	}
	
	for _, def := range behaviorFile.Behavior {
		
		BehaviorByID[def.ID] = def
		
	}
}
