// Generated by github.com/cellorigin/tool/protoc-gen-table
// DO NOT EDIT!
// Source: service.proto
package table

import (
	"proto/gamedef"
	"share"
)

var ServiceNameMap = make(map[string]*gamedef.ServiceDefine)

var ServiceWorldIDMap = make(map[int32]*gamedef.ServiceDefine)

var serviceFile gamedef.ServiceFile

func LoadServiceTable() {

	log.Infoln("load service table...")
	
	if share.LoadTable("Service", &serviceFile) != nil {
		return
	}
	
	for _, def := range serviceFile.Service {
		
		ServiceNameMap[def.Name] = def
		
		ServiceWorldIDMap[def.WorldID] = def
		
	}
}
