// Generated by github.com/cellorigin/tool/protoc-gen-table, DO NOT EDIT
// Generated from: service.proto
package table

import (
	"proto/gamedef"
	"share"
)

var serviceNameMap = make(map[string]*gamedef.ServiceDefine)

func GetServiceByName(name string) *gamedef.ServiceDefine {
	if def, ok := serviceNameMap[name]; ok {
		return def
	}
	
	return nil
	
}

var serviceWorldIDMap = make(map[int32]*gamedef.ServiceDefine)

func GetServiceByWorldID(worldid int32) *gamedef.ServiceDefine {
	if def, ok := serviceWorldIDMap[worldid]; ok {
		return def
	}
	
	return nil
	
}


var serviceFile gamedef.ServiceFile

func LoadServiceTable() {

	log.Infoln("load service table...")
	
	if share.LoadTable("Service", &serviceFile) != nil {
		return
	}
	
	for _, def := range serviceFile.Service {
		
		serviceNameMap[def.Name] = def
		
		serviceWorldIDMap[def.WorldID] = def
		
		
	}
}
