// Generated by github.com/davyxu/cellorigin
using UnityEngine;
using UnityEngine.UI;

partial class TestBoardView : Framework.BaseView
{
	TestBoardPresenter _Presenter;
	
	Text _TextInfo;
	
	public override void Bind( Framework.BasePresenter presenter )
	{
		_Presenter = presenter as TestBoardPresenter;
		
		var trans = this.transform;
		
		_TextInfo = trans.Find("TextInfo").GetComponent<Text>();
		
		_Presenter.OnTextInfoChanged += delegate()
		{
			_TextInfo.text = _Presenter.TextInfo;
		};
		if ( _Presenter.TextInfo != null )
		{
			_TextInfo.text = _Presenter.TextInfo;
		}
		
	}
	
}
