# Generated by github.com/davyxu/tabtoy
Service {IP: "127.0.0.1" Port: 8201 PeerName: "client->gate"  Enable: true  Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 8202 PeerName: "client->gate" PeerIndex: 1   Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 7201 PeerName: "svc->gate"  Enable: true  Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 7202 PeerName: "svc->gate" PeerIndex: 1   Name: "devlocal"}
