# Generated by github.com/davyxu/tabtoy
Service {MainConfig: true IP: "127.0.0.1" Port: 8101 PeerName: "client->login"  Enable: true  Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 8201 PeerName: "client->agent"  Enable: true  Name: "devlocal" DisplayName: "本地测试0"}
Service {IP: "127.0.0.1" Port: 8202 PeerName: "client->agent" PeerIndex: 1   Name: "devlocal" DisplayName: "本地测试1"}
Service {IP: "127.0.0.1" Port: 7201 PeerName: "svc->agent"  Enable: true  Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 7202 PeerName: "svc->agent" PeerIndex: 1   Name: "devlocal"}
