# Generated by github.com/davyxu/tabtoy
Service {IP: "127.0.0.1" Port: 8101 PeerName: "client->gate"  Enable: true  Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 8102 PeerName: "client->gate" PeerIndex: 1   Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 7101 PeerName: "svc->gate"  Enable: true  Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 7102 PeerName: "svc->gate" PeerIndex: 1   Name: "devlocal"}
