using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Framework
{
    class ViewTemplate
    {
        string _name;
        public ViewTemplate( string name )
        {
            _name = name;
        }

        public string ViewClassName
        {
            get { return _name + "View";  }
        }

        public string PresenterClassName
        {
            get { return _name + "Presenter"; }
        }

        public void Class( CodeGenerator gen)
        {
            gen.PrintLine("// Generated by github.com/davyxu/cellorigin");
            gen.PrintLine("using UnityEngine;");
            gen.PrintLine("using UnityEngine.UI;");
            gen.PrintLine();

            gen.PrintLine("partial class ", ViewClassName, " : Framework.BaseView");
            gen.PrintLine("{");
            gen.In();

            gen.PrintLine(PresenterClassName, " _Presenter;");

            gen.PrintLine("public override void Bind( Framework.BasePresenter presenter )");
            gen.PrintLine("{");
            gen.In();

            gen.PrintLine("_Presenter = presenter as ", PresenterClassName, ";");
            gen.PrintLine();
            gen.PrintLine("var trans = this.transform;");
            // TODO 打印控件搜索代码

            // TODO 打印控件绑定代码


            gen.Out();
            gen.PrintLine("}"); // Bind
            gen.PrintLine();

            gen.Out();
            gen.PrintLine("}"); // Class
        }

        public void ControlToVar( )
        {

        }
    }
}
