// Generated by github.com/davyxu/cellorigin UICodeGen
// DO NOT EDIT!
using UnityEngine;
using UnityEngine.UI;

public partial class LoginUI : MonoBehaviour
{
	InputField _Account;
	InputField _Address;
	Button _SetDevAddress;
	Button _SetPublicAddress;
	Dropdown _ServerList;
	Button _EnterGame;
	
	void InitUI()
	{
		_Account = GameObject.Find("/Canvas/LoginUI/Account").GetComponent<InputField>();
		_Address = GameObject.Find("/Canvas/LoginUI/Address").GetComponent<InputField>();
		_SetDevAddress = GameObject.Find("/Canvas/LoginUI/SetDevAddress").GetComponent<Button>();
		_SetPublicAddress = GameObject.Find("/Canvas/LoginUI/SetPublicAddress").GetComponent<Button>();
		_ServerList = GameObject.Find("/Canvas/LoginUI/ServerList").GetComponent<Dropdown>();
		_EnterGame = GameObject.Find("/Canvas/LoginUI/EnterGame").GetComponent<Button>();
		
		_SetDevAddress.onClick.AddListener( SetDevAddress_Click );
		_SetPublicAddress.onClick.AddListener( SetPublicAddress_Click );
		_EnterGame.onClick.AddListener( EnterGame_Click );
	}
}
