// Generated by github.com/davyxu/cellorigin UICodeGen
// DO NOT EDIT!
using UnityEngine;
using UnityEngine.UI;

public partial class LoginUI : MonoBehaviour
{
	InputField _Account;
	InputField _Address;
	Button _SetDevAddress;
	Button _SetPublicAddress;
	Button _Login;
	
	void InitUI()
	{
		_Account = GameObject.Find("/Canvas/LoginUI/Account").GetComponent<InputField>();
		_Address = GameObject.Find("/Canvas/LoginUI/Address").GetComponent<InputField>();
		_SetDevAddress = GameObject.Find("/Canvas/LoginUI/SetDevAddress").GetComponent<Button>();
		_SetPublicAddress = GameObject.Find("/Canvas/LoginUI/SetPublicAddress").GetComponent<Button>();
		_Login = GameObject.Find("/Canvas/LoginUI/Login").GetComponent<Button>();
		
		_SetDevAddress.onClick.AddListener( OnSetDevAddress );
		_SetPublicAddress.onClick.AddListener( OnSetPublicAddress );
		_Login.onClick.AddListener( OnLogin );
	}
}
