// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package proto

import (
	"reflect"

	"github.com/davyxu/goobjfmt"
	"github.com/davyxu/cellnet/codec/sproto"
)

type LoginREQ struct {
	PlatformToken string `sproto:"string,0,name=PlatformToken"`
}

func (self *LoginREQ) String() string { return goobjfmt.CompactTextString(self) }

type LoginACK struct {
	Result int32 `sproto:"integer,0,name=Result"`

	Token string `sproto:"string,1,name=Token"`
}

func (self *LoginACK) String() string { return goobjfmt.CompactTextString(self) }

type PeerConnected struct {
}

func (self *PeerConnected) String() string { return goobjfmt.CompactTextString(self) }

type PeerDisconnected struct {
}

func (self *PeerDisconnected) String() string { return goobjfmt.CompactTextString(self) }

type PeerConnectError struct {
}

func (self *PeerConnectError) String() string { return goobjfmt.CompactTextString(self) }

type PeerRecvError struct {
}

func (self *PeerRecvError) String() string { return goobjfmt.CompactTextString(self) }

type PeerSendError struct {
}

func (self *PeerSendError) String() string { return goobjfmt.CompactTextString(self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*LoginREQ)(nil)).Elem(),         // 2266274450
	reflect.TypeOf((*LoginACK)(nil)).Elem(),         // 3964561136
	reflect.TypeOf((*PeerConnected)(nil)).Elem(),    // 1162626543
	reflect.TypeOf((*PeerDisconnected)(nil)).Elem(), // 3629069126
	reflect.TypeOf((*PeerConnectError)(nil)).Elem(), // 780565736
	reflect.TypeOf((*PeerRecvError)(nil)).Elem(),    // 3264497882
	reflect.TypeOf((*PeerSendError)(nil)).Elem(),    // 4009711215
}

var SProtoEnumValue = map[string]map[int32]string{}

func init() {
	sprotocodec.AutoRegisterMessageMeta(SProtoStructs)
}
