# Generated by github.com/davyxu/tabtoy
Service {IP: "192.168.0.7" Port: 8001 PeerName: "client->gate"   Name: "devlocal"}
Service {IP: "127.0.0.1" Port: 7001 PeerName: "game->gate"   Name: "devlocal"}
