// Generated by github.com/davyxu/cellorigin UICodeGen
// DO NOT EDIT!
using UnityEngine;
using UnityEngine.UI;

public partial class CharListUI : MonoBehaviour
{
	
	void InitUI()
	{
		var trans = this.transform;
		
	}
}
