// Generated by github.com/davyxu/cellorigin UICodeGen
using UnityEngine;
using UnityEngine.UI;

public partial class CharListUI : MonoBehaviour
{
	void Awake( )
	{
		InitUI( );
        gameObject.SetActive(false);

        EventEmiiter.Instance.Add<Event.ShowCharList>(ev =>
        {
            gameObject.SetActive(true);
        });
	}
	
}
