package main

import (
	"github.com/davyxu/pbmeta"
)

func printFile(gen *Generator, file *pbmeta.FileDescriptor) {

	gen.Println("// Generated by github.com/cellorigin/tool/protoc-gen-table, DO NOT EDIT")
	gen.Println("// Generated from: ", file.FileName())

}
