package main

import (
	"proto/gamedef"

	"github.com/davyxu/pbmeta"
	"github.com/golang/protobuf/proto"
)

func getOption(arr []*pbmeta.TaggedComment) *gamedef.TableCodeOption {

	var option gamedef.TableCodeOption

	if len(arr) == 0 {
		return &option
	}

	for _, tc := range arr {

		if tc.Name == "table" {

			if err := proto.UnmarshalText(tc.Data, &option); err != nil {
				log.Errorf("parse table option failed, [%s] %s", tc.Data, err.Error())
				return &option
			}

			return &option

		}

	}

	return &option
}

func printFile(gen *Generator, file *pbmeta.FileDescriptor) {

	gen.Println("// Generated by github.com/cellorigin/tool/protoc-gen-table, DO NOT EDIT")
	gen.Println("// Generated from: ", file.FileName())

	gen.Println("package table")

	for i := 0; i < file.MessageCount(); i++ {

		msg := file.Message(i)

		if getOption(msg.ParseTaggedComment()).GenTableCode {

			printMessage(gen, msg, file)
		}

	}

}
