// Generated by github.com/davyxu/cellorigin
using UnityEngine;
using UnityEngine.UI;

partial class LoginServerInfoView : Framework.BaseItemView
{
	LoginServerInfoPresenter _Presenter;
	
	Button _Select;
	Text _Name;
	
	public override void Bind( Framework.BasePresenter presenter )
	{
		_Presenter = presenter as LoginServerInfoPresenter;
		
		var trans = this.transform;
		
		_Select = trans.Find("Select").GetComponent<Button>();
		_Name = trans.Find("Select/Name").GetComponent<Text>();
		
		_Select.onClick.AddListener( _Presenter.Cmd_Select );
		_Presenter.OnNameChanged += delegate()
		{
			_Name.text = _Presenter.Name;
		};
		if ( _Presenter.Name != null )
		{
			_Name.text = _Presenter.Name;
		}
		
	}
	
}
