// Generated by github.com/davyxu/cellorigin
using UnityEngine;
using UnityEngine.UI;

partial class LoginCharListView : Framework.BaseView
{
	LoginCharListPresenter _Presenter;
	
	InputField _CharName;
	Button _CreateChar;
	Button _DebugAdd;
	Button _DebugRemove;
	Button _DebugModify;
	Framework.ListControl _LoginCharInfo;
	
	public override void Bind( Framework.BasePresenter presenter )
	{
		_Presenter = presenter as LoginCharListPresenter;
		
		var trans = this.transform;
		
		_CharName = trans.Find("CharName").GetComponent<InputField>();
		_CreateChar = trans.Find("CreateChar").GetComponent<Button>();
		_DebugAdd = trans.Find("DebugAdd").GetComponent<Button>();
		_DebugRemove = trans.Find("DebugRemove").GetComponent<Button>();
		_DebugModify = trans.Find("DebugModify").GetComponent<Button>();
		_LoginCharInfo = trans.Find("LoginCharInfo").GetComponent<Framework.ListControl>();
		
		_Presenter.OnCharNameChanged += delegate()
		{
			_CharName.text = _Presenter.CharName;
		};
		if ( _Presenter.CharName != null )
		{
			_CharName.text = _Presenter.CharName;
		}
		
		_CreateChar.onClick.AddListener( _Presenter.Cmd_CreateChar );
		_DebugAdd.onClick.AddListener( _Presenter.Cmd_DebugAdd );
		_DebugRemove.onClick.AddListener( _Presenter.Cmd_DebugRemove );
		_DebugModify.onClick.AddListener( _Presenter.Cmd_DebugModify );
		Framework.Utility.BindCollectionView<int, LoginCharInfoPresenter, LoginCharInfoView>( _Presenter.LoginCharInfoCollection, _LoginCharInfo );
		
	}
	
}
