// Generated by github.com/davyxu/cellorigin UICodeGen
// DO NOT EDIT!
using UnityEngine;
using UnityEngine.UI;

public partial class CreateCharUI : MonoBehaviour
{
	InputField _CharName;
	Button _SelectCharA;
	Button _SelectCharB;
	
	void InitUI()
	{
		var trans = this.transform;
		_CharName = trans.Find("CharName").GetComponent<InputField>();
		_SelectCharA = trans.Find("SelectCharA").GetComponent<Button>();
		_SelectCharB = trans.Find("SelectCharB").GetComponent<Button>();
		
		_SelectCharA.onClick.AddListener( SelectCharA_Click );
		_SelectCharB.onClick.AddListener( SelectCharB_Click );
	}
}
