// Generated by github.com/davyxu/cellorigin UICodeGen
using UnityEngine;
using UnityEngine.UI;

public partial class CreateCharUI : MonoBehaviour
{
    CharListModel _model;

	void Awake( )
	{
        _model = ModelManager.Instance.Get<CharListModel>();

		InitUI( );
        _CharName.text = "hello";
	}
	
	// Button @ SelectCharA
	void SelectCharA_Click( )
	{
        _model.Create(0, _CharName.text);
	}
	
	// Button @ SelectCharB
	void SelectCharB_Click( )
	{
        _model.Create(1, _CharName.text);
	}

	
}
