// Generated by github.com/davyxu/cellorigin UICodeGen
using UnityEngine;
using UnityEngine.UI;

public partial class CreateCharUI : MonoBehaviour
{
	void Awake( )
	{
		InitUI( );

        EventDispatcher.Instance.Add<EventEnterGame>( ev =>{
            gameObject.SetActive(true);
        });
	}
	
	// Button @ SelectCharA
	void SelectCharA_Click( )
	{
	
	}
	
	// Button @ SelectCharB
	void SelectCharB_Click( )
	{
	
	}
	
	// Button @ CreateChar
	void CreateChar_Click( )
	{
	
	}
	
}
