//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DescriptorPoolWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DescriptorPool), typeof(System.Object));
		L.RegFunction("Init", Init);
		L.RegFunction("GetMessage", GetMessage);
		L.RegFunction("New", _CreateDescriptorPool);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDescriptorPool(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DescriptorPool obj = new DescriptorPool();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DescriptorPool.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DescriptorPool obj = (DescriptorPool)ToLua.CheckObject(L, 1, typeof(DescriptorPool));
			google.protobuf.FileDescriptorSet arg0 = (google.protobuf.FileDescriptorSet)ToLua.CheckObject(L, 2, typeof(google.protobuf.FileDescriptorSet));
			obj.Init(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DescriptorPool obj = (DescriptorPool)ToLua.CheckObject(L, 1, typeof(DescriptorPool));
			string arg0 = ToLua.CheckString(L, 2);
			Descriptor o = obj.GetMessage(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

