//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EnumDescriptorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(EnumDescriptor), typeof(ProtoBase));
		L.RegFunction("GetValueByName", GetValueByName);
		L.RegFunction("GetValueByNumber", GetValueByNumber);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("Define", get_Define, null);
		L.RegVar("Name", get_Name, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetValueByName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EnumDescriptor obj = (EnumDescriptor)ToLua.CheckObject(L, 1, typeof(EnumDescriptor));
			string arg0 = ToLua.CheckString(L, 2);
			EnumValueDescriptor o = obj.GetValueByName(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetValueByNumber(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EnumDescriptor obj = (EnumDescriptor)ToLua.CheckObject(L, 1, typeof(EnumDescriptor));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			EnumValueDescriptor o = obj.GetValueByNumber(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Define(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			EnumDescriptor obj = (EnumDescriptor)o;
			google.protobuf.EnumDescriptorProto ret = obj.Define;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Define on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			EnumDescriptor obj = (EnumDescriptor)o;
			string ret = obj.Name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Name on a nil value" : e.Message);
		}
	}
}

