//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PeerManagerLuaWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PeerManagerLua), typeof(Singleton<PeerManagerLua>));
		L.RegFunction("Get", Get);
		L.RegFunction("New", _CreatePeerManagerLua);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePeerManagerLua(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				PeerManagerLua obj = new PeerManagerLua();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: PeerManagerLua.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Get(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PeerManagerLua obj = (PeerManagerLua)ToLua.CheckObject(L, 1, typeof(PeerManagerLua));
			string arg0 = ToLua.CheckString(L, 2);
			NetworkPeerLua o = obj.Get(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

